#!/usr/bin/env python
message = """
   _         _                 _   _                 
  /_\  _ __ (_)_ __ ___   __ _| |_(_) ___  _ __  ___ 
 //_\\\| '_ \| | '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
/  _  \ | | | | | | | | | (_| | |_| | (_) | | | \__ \ 
\_/ \_/_| |_|_|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/



- Why?
	- They are attractive.

	- Iterating over a time course and see the progression of your data
	  reveal some interesting patterns.

	- Good for presentations.

	- Integrates metadata in a useful manner.





"""
print message