#!/usr/bin/env python
message = """
   ___       _   _ _            
  /___\_   _| |_| (_)_ __   ___ 
 //  // | | | __| | | '_ \ / _ \ 
/ \_//| |_| | |_| | | | | |  __/
\___/  \__,_|\__|_|_|_| |_|\___|


- Animations tab in Emperor:
	- New feature, enabling users to do what we do for video animations.

	- Source code and structure of the two key components.

	https://github.com/qiime/emperor/pull/234

- Unit testing in JavaScript using QUnit:
	- The code base in Emperor has been growing a lot not only on the Python
	side of things but also in JavaScript.

	- The code is now not only dealing with UI elements.

	- Allows integration with Travis and Jenkins for CI.

"""
print message