#!/usr/bin/env python
message = """







                               ___                     
                              /   \___ _ __ ___   ___  
                             / /\ / _ \ '_ ` _ \ / _ \ 
                            / /_//  __/ | | | | | (_) |
                           /___,' \___|_| |_| |_|\___/ 
                            


                           Go to:

                           http://goo.gl/nmvm2p





"""
print message