#!/usr/bin/env python
message = """
     ___          _      
    / __\___   __| | ___ 
   / /  / _ \ / _` |/ _ \ 
  / /___ (_) | (_| |  __/ 
  \____/\___/ \__,_|\___| 

                            

	- Go to github.com/qiime/emperor look at the pull requests
	  (only open one), go to files changed and look for:

		animate.js

		trajectory.js








"""
print message