#!/usr/bin/env python
message = """
   ____                  _ _   
  /___ \     /\ /\ _ __ (_) |_ 
 //  / /____/ / \ \ '_ \| | __|
/ \_/ /_____\ \_/ / | | | | |_ 
\___,_\      \___/|_| |_|_|\__|



	- Part of the jQuery software foundation.

	- Works kinda like python's unit testing framework.

	- Super easy to setup.

	- Integration with Travis/Jenkins.

	- Useful error messages.





"""
print message