#!/usr/bin/env python
message = """
   _         _                 _   _                 
  /_\  _ __ (_)_ __ ___   __ _| |_(_) ___  _ __  ___ 
 //_\\\| '_ \| | '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|
/  _  \ | | | | | | | | | (_| | |_| | (_) | | | \__ \ 
\_/ \_/_| |_|_|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/



- Problems
	- They are __really__ time consuming to create.

	- It's not easy to iterate over.

	- Depends on Mathematica (proprietary software).
		- Mathematica's 3D backend is broken (segfaults, memory leaks).

	- Requires a lot of resources.

	- A lot of extra code (github.com/ElDeveloper/apocaqiime).

	- Frustrating.

"""
print message