#!/usr/bin/env python
message = """






 _____ _                 _          _ 
/__   \ |__   __ _ _ __ | | _____  / \ 
  / /\/ '_ \ / _` | '_ \| |/ / __|/  /
 / /  | | | | (_| | | | |   <\__ \\\_/ 
 \/   |_| |_|\__,_|_| |_|_|\_\___/( )





 Slides available in:
 github.com/ElDeveloper/code-review/





"""
print message