#!/usr/bin/env python
message = """
   __                   __           _       _   
   \ \  __ ___   ____ _/ _\ ___ _ __(_)_ __ | |_ 
    \ \/ _` \ \ / / _` \ \ / __| '__| | '_ \| __|
 /\_/ / (_| |\ V / (_| |\ \ (__| |  | | |_) | |_ 
 \___/ \__,_| \_/ \__,_\__/\___|_|  |_| .__/ \__|
                                      |_|        

             _ _     _____         _   _             
 /\ /\ _ __ (_) |_  /__   \___ ___| |_(_)_ __   __ _ 
/ / \ \ '_ \| | __|   / /\/ _ \ __| __| | '_ \ / _` |
\ \_/ / | | | | |_   / / |  __\__ \ |_| | | | | (_| |
 \___/|_| |_|_|\__|  \/   \___|___/\__|_|_| |_|\__, |
                                               |___/ 


    - Several projects in the lab use JavaScript.

    - Not all of them use unit testing.

    - It makes the programming experience _much_ better.


"""
print message