#!/usr/bin/env python
# -*- coding: utf-8 -*-
message = u"""
   ___                _     _                _   _                 
  / __\___  _ __  ___(_) __| | ___ _ __ __ _| |_(_) ___  _ __  ___ 
 / /  / _ \| '_ \/ __| |/ _` |/ _ \ '__/ _` | __| |/ _ \| '_ \/ __|
/ /___ (_) | | | \__ \ | (_| |  __/ | | (_| | |_| | (_) | | | \__ \ 
\____/\___/|_| |_|___/_|\__,_|\___|_|  \__,_|\__|_|\___/|_| |_|___/

                            

	- Should these be distributed with every visualization?

	- What other code in QIIME/* lacks unit tests?

	- ¿Questions?








""".encode("utf-8") # http://stackoverflow.com/a/6179012/379593
print message